spring.application.name=medicnote-backend

spring.datasource.url=jdbc:mysql://localhost:3306/medicnote?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

server.port=8080




jwt.secret=your_super_secret_key_which_is_long_enough_123456


# styling in cli
spring.output.ansi.enabled=ALWAYS